from sympy import *
def get_M():
	I_xxf = Symbol('I_xxf')
	I_xxw = Symbol('I_xxw')
	l_f = Symbol('l_f')
	m_f = Symbol('m_f')
	s = Symbol('s')
	sigma = Symbol('sigma')
	t = Symbol('t')
	m_w = Symbol('m_w')
	y_w = Symbol('y_w')
	z_w = Symbol('z_w')
	q1 = Function('q1')
	q2 = Function('q2')
	e = MutableDenseMatrix([[2*I_xxf + I_xxw + 2*l_f**2*m_f - l_f*m_f*s*sigma*cos(q1(t)) - l_f*m_f*s*sigma*cos(q2(t)) + l_f*m_f*s*cos(q1(t)) + l_f*m_f*s*cos(q2(t)) + m_f*s**2*sigma**2/2 - m_f*s**2*sigma + m_f*s**2/2 + m_w*y_w**2 + m_w*z_w**2, -I_xxf - l_f**2*m_f + l_f*m_f*s*sigma*cos(q1(t))/2 - l_f*m_f*s*cos(q1(t))/2, I_xxf + l_f**2*m_f - l_f*m_f*s*sigma*cos(q2(t))/2 + l_f*m_f*s*cos(q2(t))/2], [-I_xxf - l_f**2*m_f + l_f*m_f*s*sigma*cos(q1(t))/2 - l_f*m_f*s*cos(q1(t))/2, I_xxf + l_f**2*m_f, 0], [I_xxf + l_f**2*m_f - l_f*m_f*s*sigma*cos(q2(t))/2 + l_f*m_f*s*cos(q2(t))/2, 0, I_xxf + l_f**2*m_f]])
	return e
def get_f():
	g = Symbol('g')
	m_f = Symbol('m_f')
	l_f = Symbol('l_f')
	t = Symbol('t')
	s = Symbol('s')
	sigma = Symbol('sigma')
	m_w = Symbol('m_w')
	y_w = Symbol('y_w')
	z_w = Symbol('z_w')
	q0 = Function('q0')
	q1 = Function('q1')
	q2 = Function('q2')
	e = ImmutableDenseMatrix([[-g*m_f*(-l_f*(-sin(q0(t))*sin(q1(t)) - cos(q0(t))*cos(q1(t))) - s*(sigma/2 + Rational(-1, 2))*cos(q0(t))) - g*m_f*(-l_f*(-sin(q0(t))*sin(q2(t)) + cos(q0(t))*cos(q2(t))) - s*(Rational(1, 2) - sigma/2)*cos(q0(t))) - g*m_w*(y_w*cos(q0(t)) - z_w*sin(q0(t))) + l_f*m_f*s*sigma*sin(q1(t))*Derivative(q0(t), t)*Derivative(q1(t), t) - l_f*m_f*s*sigma*sin(q1(t))*Derivative(q1(t), t)**2/2 + l_f*m_f*s*sigma*sin(q2(t))*Derivative(q0(t), t)*Derivative(q2(t), t) + l_f*m_f*s*sigma*sin(q2(t))*Derivative(q2(t), t)**2/2 - l_f*m_f*s*sin(q1(t))*Derivative(q0(t), t)*Derivative(q1(t), t) + l_f*m_f*s*sin(q1(t))*Derivative(q1(t), t)**2/2 - l_f*m_f*s*sin(q2(t))*Derivative(q0(t), t)*Derivative(q2(t), t) - l_f*m_f*s*sin(q2(t))*Derivative(q2(t), t)**2/2], [g*l_f*m_f*(sin(q0(t))*sin(q1(t)) + cos(q0(t))*cos(q1(t))) - l_f*m_f*s*sigma*sin(q1(t))*Derivative(q0(t), t)**2/2 + l_f*m_f*s*sin(q1(t))*Derivative(q0(t), t)**2/2], [g*l_f*m_f*(-sin(q0(t))*sin(q2(t)) + cos(q0(t))*cos(q2(t))) - l_f*m_f*s*sigma*sin(q2(t))*Derivative(q0(t), t)**2/2 + l_f*m_f*s*sin(q2(t))*Derivative(q0(t), t)**2/2]])
	return e
def get_T():
	I_xxf = Symbol('I_xxf')
	t = Symbol('t')
	I_xxw = Symbol('I_xxw')
	l_f = Symbol('l_f')
	m_f = Symbol('m_f')
	s = Symbol('s')
	sigma = Symbol('sigma')
	m_w = Symbol('m_w')
	y_w = Symbol('y_w')
	z_w = Symbol('z_w')
	q0 = Function('q0')
	q1 = Function('q1')
	q2 = Function('q2')
	e = I_xxf*Derivative(q0(t), t)**2 - I_xxf*Derivative(q0(t), t)*Derivative(q1(t), t) + I_xxf*Derivative(q0(t), t)*Derivative(q2(t), t) + I_xxf*Derivative(q1(t), t)**2/2 + I_xxf*Derivative(q2(t), t)**2/2 + I_xxw*Derivative(q0(t), t)**2/2 + l_f**2*m_f*Derivative(q0(t), t)**2 - l_f**2*m_f*Derivative(q0(t), t)*Derivative(q1(t), t) + l_f**2*m_f*Derivative(q0(t), t)*Derivative(q2(t), t) + l_f**2*m_f*Derivative(q1(t), t)**2/2 + l_f**2*m_f*Derivative(q2(t), t)**2/2 - l_f*m_f*s*sigma*cos(q1(t))*Derivative(q0(t), t)**2/2 + l_f*m_f*s*sigma*cos(q1(t))*Derivative(q0(t), t)*Derivative(q1(t), t)/2 - l_f*m_f*s*sigma*cos(q2(t))*Derivative(q0(t), t)**2/2 - l_f*m_f*s*sigma*cos(q2(t))*Derivative(q0(t), t)*Derivative(q2(t), t)/2 + l_f*m_f*s*cos(q1(t))*Derivative(q0(t), t)**2/2 - l_f*m_f*s*cos(q1(t))*Derivative(q0(t), t)*Derivative(q1(t), t)/2 + l_f*m_f*s*cos(q2(t))*Derivative(q0(t), t)**2/2 + l_f*m_f*s*cos(q2(t))*Derivative(q0(t), t)*Derivative(q2(t), t)/2 + m_f*s**2*sigma**2*Derivative(q0(t), t)**2/4 - m_f*s**2*sigma*Derivative(q0(t), t)**2/2 + m_f*s**2*Derivative(q0(t), t)**2/4 + m_w*y_w**2*Derivative(q0(t), t)**2/2 + m_w*z_w**2*Derivative(q0(t), t)**2/2
	return e
def get_U():
	g = Symbol('g')
	m_f = Symbol('m_f')
	l_f = Symbol('l_f')
	t = Symbol('t')
	s = Symbol('s')
	sigma = Symbol('sigma')
	m_w = Symbol('m_w')
	y_w = Symbol('y_w')
	z_w = Symbol('z_w')
	q0 = Function('q0')
	q1 = Function('q1')
	q2 = Function('q2')
	e = g*m_f*(l_f*(-sin(q0(t))*cos(q1(t)) + sin(q1(t))*cos(q0(t))) - s*(1 - sigma)*sin(q0(t))/2) + g*m_f*(-l_f*(-sin(q0(t))*cos(q2(t)) - sin(q2(t))*cos(q0(t))) + s*(1 - sigma)*sin(q0(t))/2) + g*m_w*(-y_w*sin(q0(t)) - z_w*cos(q0(t)))
	return e
def get_Q():
	V = Symbol('V')
	a0 = Symbol('a0')
	c = Symbol('c')
	rho = Symbol('rho')
	s = Symbol('s')
	sigma = Symbol('sigma')
	Lambda = Symbol('Lambda')
	t = Symbol('t')
	a1 = Symbol('a1')
	a2 = Symbol('a2')
	a3 = Symbol('a3')
	a30 = Symbol('a30')
	a31 = Symbol('a31')
	a32 = Symbol('a32')
	a33 = Symbol('a33')
	a34 = Symbol('a34')
	a35 = Symbol('a35')
	a36 = Symbol('a36')
	a37 = Symbol('a37')
	a38 = Symbol('a38')
	a39 = Symbol('a39')
	a4 = Symbol('a4')
	a5 = Symbol('a5')
	a6 = Symbol('a6')
	a7 = Symbol('a7')
	a8 = Symbol('a8')
	a9 = Symbol('a9')
	a10 = Symbol('a10')
	a11 = Symbol('a11')
	a12 = Symbol('a12')
	a13 = Symbol('a13')
	a14 = Symbol('a14')
	a15 = Symbol('a15')
	a16 = Symbol('a16')
	a17 = Symbol('a17')
	a18 = Symbol('a18')
	a19 = Symbol('a19')
	a20 = Symbol('a20')
	a21 = Symbol('a21')
	a22 = Symbol('a22')
	a23 = Symbol('a23')
	a24 = Symbol('a24')
	a25 = Symbol('a25')
	a26 = Symbol('a26')
	a27 = Symbol('a27')
	a28 = Symbol('a28')
	a29 = Symbol('a29')
	q2 = Function('q2')
	q0 = Function('q0')
	q1 = Function('q1')
	e = MutableDenseMatrix([[-V**2*a0*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-19*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-19*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-19*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a1*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-17*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-17*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-17*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a2*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q2(t), t)/8 + (-3*s*sigma*cos(Lambda)/8 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-3*s*sigma*cos(Lambda)/8 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a3*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-13*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-13*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-13*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a30*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a31*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (3*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(3*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a32*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-s*sigma*cos(Lambda)*Derivative(q1(t), t)/8 + (s*sigma*cos(Lambda)/8 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(s*sigma*cos(Lambda)/8 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a33*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-7*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (7*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(7*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a34*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-9*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (9*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(9*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a35*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-11*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (11*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(11*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a36*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-13*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (13*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(13*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a37*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q1(t), t)/8 + (3*s*sigma*cos(Lambda)/8 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(3*s*sigma*cos(Lambda)/8 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a38*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-17*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (17*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(17*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a39*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q1(t))) + (-19*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (19*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*(19*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)/40 - V**2*a4*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-11*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-11*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-11*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a5*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-9*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-9*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-9*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a6*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-7*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-7*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-7*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a7*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-s*sigma*cos(Lambda)*Derivative(q2(t), t)/8 + (-s*sigma*cos(Lambda)/8 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-s*sigma*cos(Lambda)/8 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a8*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-3*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-3*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - V**2*a9*c*rho*s*sigma*(-atan(sin(Lambda)*tan(q2(t))) + (-s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*(-s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)/40 - 361*V*a10*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 289*V*a11*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 9*V*a12*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/2560 - 169*V*a13*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 121*V*a14*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 81*V*a15*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 49*V*a16*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - V*a17*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/2560 - 9*V*a18*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - V*a19*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - V*a20*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 9*V*a21*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - V*a22*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/2560 - 49*V*a23*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 81*V*a24*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 121*V*a25*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 169*V*a26*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 9*V*a27*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/2560 - 289*V*a28*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000 - 361*V*a29*c*rho*s**3*(1 - sigma)**3*Derivative(q0(t), t)/64000], [V**2*a30*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 3*V**2*a31*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (3*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + V**2*a32*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-s*sigma*cos(Lambda)*Derivative(q1(t), t)/8 + (s*sigma*cos(Lambda)/8 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/320 + 7*V**2*a33*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-7*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (7*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 9*V**2*a34*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-9*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (9*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 11*V**2*a35*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-11*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (11*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 13*V**2*a36*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-13*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (13*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 3*V**2*a37*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q1(t), t)/8 + (3*s*sigma*cos(Lambda)/8 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/320 + 17*V**2*a38*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-17*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (17*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 19*V**2*a39*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q1(t))) + (-19*s*sigma*cos(Lambda)*Derivative(q1(t), t)/40 + (19*s*sigma*cos(Lambda)/40 - s*sigma*cos(q1(t))/2 + s*cos(q1(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600], [19*V**2*a0*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-19*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-19*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 17*V**2*a1*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-17*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-17*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 3*V**2*a2*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q2(t), t)/8 + (-3*s*sigma*cos(Lambda)/8 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/320 + 13*V**2*a3*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-13*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-13*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 11*V**2*a4*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-11*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-11*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 9*V**2*a5*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-9*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-9*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + 7*V**2*a6*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-7*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-7*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + V**2*a7*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-s*sigma*cos(Lambda)*Derivative(q2(t), t)/8 + (-s*sigma*cos(Lambda)/8 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/320 + 3*V**2*a8*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-3*s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-3*s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600 + V**2*a9*c*rho*s**2*sigma**2*(-atan(sin(Lambda)*tan(q2(t))) + (-s*sigma*cos(Lambda)*Derivative(q2(t), t)/40 + (-s*sigma*cos(Lambda)/40 + s*sigma*cos(q2(t))/2 - s*cos(q2(t))/2)*Derivative(q0(t), t))/V)*cos(Lambda)/1600]])
	return e
